volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    env_file: .env
    volumes:
      - static:/app/strides/static
      - media:/app/strides/media
    depends_on:
      - db
    expose:
      - "8000"

  gateway:
    build: ./gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
    ports:
      - "8000:80"