# Generated by Django 5.0.6 on 2025-09-29 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "applicant_type",
                    models.CharField(
                        choices=[
                            ("self", "Я и есть подопечный"),
                            ("parent", "Мать/отец"),
                            ("guardian", "Опекун"),
                            ("relative", "Родственник"),
                        ],
                        default="self",
                        max_length=16,
                    ),
                ),
                (
                    "subject_full_name",
                    models.CharField(max_length=255, verbose_name="ФИО подопечного"),
                ),
                (
                    "subject_dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения подопечного"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Телефон"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Отправлена"),
                            ("review", "Необходима проверка"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
