# Generated by Django 5.0.6 on 2025-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodvizhenielifeuser",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
