# Generated by Django 5.0.6 on 2025-10-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_prodvizhenielifeuser_telegram_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prodvizhenielifeuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
